name: pub_wbcli
version: 0.0.1
description: pub wb flutter study by rxdart
dependencies:
  rxdart: ^0.20.0
environment:
  sdk: '>=2.0.0 <3.0.0'
authors:
  - wang haijun <haijun.goo@gmail.com>
homepage: https://github.com/153493932/pub_wb_hello